# Basic Python Syntax

**Learning Objective:** identify and use the basic syntax of the Python language including variables, functions, objects and packages.

This notebook is meant to provide the absolute minimal syntax needed to start using Python packages such as NumPy, SciPy, Matplotlib, etc. for data science. For a full tutorial to the Python language see [codecademy's](http://www.codecademy.com/) excellent [Python Course](http://www.codecademy.com/tracks/python).

## Objects

* Objects are the **nouns** of the Python programming language.
* Objects are the virtual equivalent of "people, places and things."
* Objects typically encode some sort of **data**

Here are some examples of objects.

An `str`, or string, is a bit of text:

In [1]:
"Hi there"

'Hi there'

An `int`, or integer, is a number without a decimal point:

In [2]:
12345

12345

A `float`, or floating point number, is a number with a decimal point:

In [3]:
3.141

3.141

Some objects are containers. That is, they *contain* other objects. Here is a `list`, which is an ordered sequence objects:

In [4]:
[0,1,2,3,4,5]

[0, 1, 2, 3, 4, 5]

Here is a `dict`, or dictionary. A `dict` is an unordered pair of `{'key': value}` pairs:

In [5]:
{'name': 'Bart Simpson',
 'address': '742 Evergreen Terrace'}

{'address': '742 Evergreen Terrace', 'name': 'Bart Simpson'}

In [6]:
True, False

(True, False)

## Variables

* A variable is a way of naming or labeling an object.
* A variable is created using a single `=` sign.

Create a variable named `a` with the value `Hi There`:

In [8]:
a = 'Hi There'

Notice that there is no output when a variable is created. To see the value of a variable, you can use the `print` function:

In [9]:
print(a)

Hi There


Create a variable named `b` with the value `12345`:

In [10]:
b = 12345

Create a variable named `c` with the value `3.141`:

In [11]:
c = 3.141

Create variables `c` and `d` pointing to a list and a dict:

In [12]:
d = [0,1,2,3,4,5]

In [13]:
e = {'name': 'Bart Simpson',
     'address': '742 Evergreen Terrace'}

## Functions

* If objects are the **nouns** of Python syntax, then `functions` are the **verbs**.
* Functions perform actions on objects.
* In Python, functions are defined and called with parentheses `()`.

Let's define a simple function `f` that returns the sum of its arguments `x` and `y`:

In [14]:
def f(x,y):
    return x+y

We "call" the function with the exact same notation we would use in mathematics:

In [15]:
f(2,2)

4

Another way of calling a function is by explicitely naming the arguments:

In [16]:
f(x=2,y=2)

4

Here the arguments are passed as **keywords**.

If you don't know how a function works, you can use `?` to get help:

In [17]:
import math

In [18]:
math.cos?

Type:        builtin_function_or_method
String form: <built-in function cos>
Docstring:
cos(x)

Return the cosine of x (measured in radians).


## Object containment

* Objects can **contain** other objects
* There are two types of containment:
  - One to one, indicated by `.`

In [19]:
class Student():
    pass

In [20]:
bart = Student()

A student has a `name` and `address` that are accessed using a `.`:

In [21]:
bart.name = "Bart Simpson"
bart.address = "742 Evergreen Terrace"

In [22]:
bart.name

'Bart Simpson'

In [23]:
bart.address

'742 Evergreen Terrace'

Notice how the objects contained inside a `Student` themselves have names (they are variables). Variables that are attached to objects are called **attributes**.

You can use "tab completion" to inspect what attributes an object has:

In [ ]:
bart.

## Functions attached to objects

* Objects can have functions attached to them.
* For example we might want to *start* a *car*.
* In Python, functions attached to objects are called "methods".
* A method involves **containment** and a **verb** so you need to use both `.` and `()`.

Here is a Python list:

In [3]:
colors = ['blue', 'red', 'green']

The list object can be sorted using the `sort` method:

In [5]:
colors.sort()

In [6]:
colors

['blue', 'green', 'red']

## Coding style

There are some common conventions used in the Python community for naming things. While these conventions are not hard and fast, they help your code to be more readable. Here are the basics:

* Variables, attributes, functions and method should be named with `lowercase_and_underscores`
* Classes should be named with `FirstLetterCaps`

## Resources

* The full [Python Documentation](https://docs.python.org/2/).
* The [Python Style Guide](http://legacy.python.org/dev/peps/pep-0008/), or "PEP8," describes the recommended conventions for writing Python code.